App/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static


from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('file_upload.urls', namespace='file_upload ')),
    # url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),

]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

file_upload/urls.py
from django.contrib import admin
from django.urls import path
from . import views

from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter


router = DefaultRouter()
router.register(r'file_upload', views.DocumentViewSet)



app_name = 'file_upload'
urlpatterns = [
    path('index/', views.filelist_view, name='file_list'),
    path('file_upload/', views.model_form_upload , name = 'upload'),
    path('edit/<int:pk>', views.file_update, name='file_edit'),
    path('delete/<int:pk>', views.file_delete, name='file_delete_model'),
    url(r'^api/', include(router.urls))



]

file_upload/models.py
from django.db import models
from django.urls import reverse


from django.db.models.signals import post_delete
from django.dispatch import receiver
import os


class Document(models.Model):
    
    title = models.CharField(max_length=200,default='Model')
    description = models.CharField(max_length=255, blank=True)
    version = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='Files')
    uploaded_at = models.DateTimeField(auto_now_add=True)


    
    class Meta:
        db_table = 'file'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('file_edit', kwargs={'pk': self.pk})



@receiver(post_delete, sender=Document)
def submission_delete(sender, instance, **kwargs):
    removes = []
    if instance.document:
        model = instance.document.path.replace('zip', 'onnx')
        patch = instance.document.path.replace('zip', 'patch')
        upload_file = instance.document.path
        removes.append(model)
        removes.append(patch)
        removes.append(upload_file)
        for files in removes:
            if os.path.isfile(files):
                os.remove(files) 

        

class Widget(models.Model):
    name = models.CharField(max_length=140)

file_upload/views.py
from django.shortcuts import render
from file_upload.froms import DocumentForm
from django.shortcuts import redirect
from .models import Document
from django.core.files.storage import FileSystemStorage
from django.views.generic import ListView, DetailView,UpdateView
from django.shortcuts import (get_object_or_404, 
                              render, 
                              HttpResponseRedirect)        
from django.forms import ModelForm

from django.conf import settings                  
import json  
from .tasks import diff_mqtt_task
from django.http import HttpResponse
from django.template import loader
from django.core import serializers
from rest_framework.response import Response
from rest_framework import status,permissions
from rest_framework import viewsets

from file_upload.serializers import DocumentSerializer
from .process import folder_exists,file_rename



class FileForm(ModelForm):
    class Meta:
        model = Document
        fields = ['title', 'description','version', 'document']



def model_form_upload(request):

    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            context ={} 
            context["dataset"] = Document.objects.all()

            group_folder = folder_exists(context["dataset"])

            diff_files,upload_files,patch_files,zip_path,tmp_file_path,version = file_rename(group_folder)
    

            diff_mqtt_task.delay(diff_files,upload_files,patch_files,zip_path,tmp_file_path,version)
            # diff_mqtt_task.delay(file_rename(group_folder))
                



            
       
            return HttpResponseRedirect("/index/")
    else:
        form = DocumentForm()
    return render(request, 'model_form_upload.html', {'form': form})


def filelist_view(request): 
    
    context ={} 
    context["dataset"] = Document.objects.all()
    context["group"] = Document.objects.values('title').distinct()

    data_serializers = serializers.serialize("json", Document.objects.all())
    JSON_data = JSON_process(data_serializers,context['group'])
    context["JSON_data"] = JSON_data 
    template = loader.get_template("model_list_view.html")
    res = template.render(context,request)



    return HttpResponse(res) 




def JSON_process(data,group_data):
    data = json.loads(data)
    process_data = []
    JSON_data = {}


    for count in range(len(data)):
        groups = ({'pk':data[count]['pk']})
        groups.update(data[count]['fields'])
        process_data.append(groups)

    for count in range(len(group_data)):
        JSON_data.setdefault(list(group_data[count].values())[0],[])

    for count in range(len(process_data)):
        for key in JSON_data.keys():
            if key == (process_data[count]['title']):
                JSON_data[key].append(process_data[count])

    return JSON_data




def file_update(request, pk, template_name='file_update.html'):
    file= get_object_or_404(Document, pk=pk)
    form = FileForm(request.POST or None, instance=file)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/index/")
    return render(request, template_name, {'form':form})



def file_delete(request, pk, template_name='file_confirm_delete.html'):
    file= get_object_or_404(Document, pk=pk)

    if request.method=='POST':
        print(file)

        file.delete()


        
        
        return HttpResponseRedirect("/index/")
    return render(request, template_name, {'object':file})






class DocumentViewSet(viewsets.ModelViewSet):
    queryset = Document.objects.all()
    serializer_class = DocumentSerializer

file_upload/templates/file_confirm_delete.html
<h1>File Delete</h1>
<form method="post">{% csrf_token %}
    確定要刪除 "{{ object }}" 檔案嗎?
    <input type="submit" value="Submit" />
</form>

file_upload/templates/file_update.html
<h1>ModelFile Edit</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

file_upload/templates/model_form_base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- favicon -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- custom css & js-->
    <link rel="stylesheet" href={% static 'css/model_form_style.css' %}>
    <script src={% static 'js/model_form_main.js' %} defer></script>

    <title>upload file</title>
  </head>
  <body>
    <div class="container mt-3">
        {% block content %}
        {% endblock content %}
    </div>
  </body>
</html>

file_upload/templates/model_form_upload.html
{% extends "model_form_base.html" %}

{% block content %}

<!DOCTYPE html>
<html>
  <head>
    <title>Contact form</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">


  </head>
  <body>
    <div class="main-block">
      <div class="left-part">
        <i class="fas fa-envelope"></i>
        <i class="fas fa-at"></i>
        <i class="fas fa-mail-bulk"></i>

      </div>
        <form  id="upload-form" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{form.as_p}}
          <div id="alert-box" class="text-center mt-3"></div>

          <div id="progress-box" class="not-visible">progress</div>
          <button id="sent-data" type="submit">Upload</button>

          <div id="spinner-box" class="text-center mt-3">
            <div class="spinner-border text-primary" role="status"></div>
          </div>
          <div id="data-box" class="text-center mt-3"></div>

        </form>

    </div>
  </body>
</html>

{% endblock content %}

file_upload/templates/model_list_view.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>

    <link rel="stylesheet" href={% static 'css/index.css' %}>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js">
    </script>
  </head>

  <body>
    <div class="container">
  <div class="row">
    {% csrf_token %}

  <p></p>
  <h1>Model管理平台</h1>
  <p> </p><p> </p>

      <div class="col-md-10 col-md-offset-1">

          <div class="panel panel-default panel-table">
            <div class="panel-heading">
              <div class="row">
                <div class="col col-xs-6">
                  <h3 class="panel-title">所有檔案清單</h3>
                </div>
                <div class="col col-xs-6 text-right">
                  <button type="button" class="btn btn-sm btn-primary btn-create" 
                  onclick="window.location.href='{% url 'file_upload:upload' %}';"
                  >檔案上傳</button>
                </div>
              </div>
            </div>
            <div class="panel-body">
              <table class="table table-striped table-bordered table-list">
                <thead>
                  <tr>
                      <th><em class="fa fa-cog"></em></th>
                      <th class="hidden-xs">群組</th>
                      <th>版本</th>
                      <th>說明</th>
                      <th>上傳時間</th>
                      <!-- <th>下載</th> -->
                      <th>補丁</th>
                      <th>壓縮檔</th>
                  </tr> 
                </thead>
                <tbody>

                  {% for group,value in JSON_data.items %}

                        <tr>
                          
                          <td >

                            <table>
                              <tr>
                                <div>setting<div>
                                {% for i in value%}
                                
                                <td id="demo-{{ value.0.title }}" class="collapse multi-collapse">
                                  <a  href="{% url 'file_upload:file_edit' i.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
                                  <a  href="{% url 'file_upload:file_delete_model' i.pk %}"><span class="glyphicon glyphicon-trash"></a>
                                </td>

                                  {% endfor %} 

                              </tr>
                            </table>

                          </td>
                          
                          <!-- <button type="button" class="fa fa-chevron-right rotate" data-toggle="collapse"
                            data-target="#demo-{{ r.pk }}"> -->
                            
                          <td class="hidden-xs" type="button" class="fa fa-chevron-right rotate" data-toggle="collapse"
                          data-target=".multi-collapse" aria-expanded="false" aria-controls="demo-{{ value.0.title }} demo-{{ value.0.title }}" >{{ value.0.title }}</td>
                          
                          <td>{{value.0.version}}
                            <table>
                              <tr>
                                {% for i in value%}

                                <td id="demo-{{ value.0.title }}" class="collapse multi-collapse">
                                  <div class="col-2">{{i.version}}</div>

                                  {% endfor %} 

                              </tr>
                            </table>
                          </td>

                          </td>





                          <td>{{ value.0.description }}
                            <table>
                              <tr>
                                {% for i in value%}

                                <td id="demo-{{ value.0.title }}" class="collapse multi-collapse">
                                  <div class="col-2">{{i.description}}</div>

                                  {% endfor %} 

                              </tr>
                            </table>

                          </td>

                          <td>{{ value.0.uploaded_at }}
                            <table>
                              <tr>
                                {% for i in value%}

                                <td id="demo-{{ value.0.title }}" class="collapse multi-collapse">
                                  <div class="col-2">{{i.uploaded_at}}</div>

                                  {% endfor %} 

                              </tr>
                            </table>


                          </td>

                    
                          <!-- <td><div>Model</div>
                            <table>
                              <tr>
                                <td id="demo-{{ value.0.title }}" class="collapse multi-collapse">
                                  {% for i in value%}
                                  docker linux
                                  <div><a href="http://127.0.0.1:8888/media/Files/{{i.title}}/{{i.title}}-{{i.version}}.h5" download>{{i.version}}</a>
                                  win10
                                  <div><a href="http://192.168.50.199:8888/media/Files/{{i.title}}/{{i.title}}-{{i.version}}.h5" download>{{i.version}}</a>

                                  {% endfor %} 
                                 </td>
                              </tr>
                            </table>

                            
                          </td> -->

                          <td><div>Patch</div>
                            <table>
                              <tr>
                                <td id="demo-{{ value.0.title }}" class="collapse multi-collapse">
                                  {% for i in value%}
                                    {% if i.version != "1.0.0" %}
                                    <!-- docker linux -->
                                    <!-- <div><a href="http://127.0.0.1:8888/media/Files/{{i.title}}/{{i.title}}-{{i.version}}.patch" download>{{i.version}}</a> -->
                                    
                                    <!-- win10 -->
                                    <div><a href="http://192.168.50.199:8888/media/Files/{{i.title}}/{{i.title}}-{{i.version}}.patch" download>{{i.version}}</a>
                                        {% else %}
                                      <div>Not Patch</a>
                                    {% endif %}


                                  {% endfor %} 
                                 </td>
                              </tr>
                            </table>

                            
                          </td>

                          <td><div>Zip</div>
                            <table>
                              <tr>
                                <td id="demo-{{ value.0.title }}" class="collapse multi-collapse">
                                  {% for i in value%}
                                  <!-- docker linux -->
                                  <!-- <div><a href="http://127.0.0.1:8888/media/Files/{{i.title}}/{{i.title}}-{{i.version}}.zip" download>{{i.version}}.zip</a> -->
                                  
                                  <!-- win10 -->
                                  <div><a href="http://192.168.50.199:8888/media/Files/{{i.title}}/{{i.title}}-{{i.version}}.zip" download>{{i.version}}.zip</a>


                                  {% endfor %} 
                                 </td>
                              </tr>
                            </table>

                            
                          </td>

                        </tr>
                        {% endfor %} 
                      </tbody>
              </table>
          
            </div>
            <div class="panel-footer">
              <div class="row">
                <div class="col col-xs-4">Page 1 of 5
                </div>
                <div class="col col-xs-8">
                  <ul class="pagination hidden-xs pull-right">
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                  </ul>
                  <ul class="pagination visible-xs pull-right">
                      <li><a href="#">«</a></li>
                      <li><a href="#">»</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

</div></div></div>

  </body>